### ISSUE TITLE
make training problem

### ISSUE THREAD

**Issue by orangebacked** [OCR-D/ocrd-train#17]
Hello!
I'm trying to run the makefile with the test set provided in the directory without success. I created the .box filesm but the script end with this error when i run Make training:

combine_tessdata -u /home/tulipan1637/Documents/Emiliano/OCR/OCRtraining/ocrd-train/usr/share/tessdata /foo.traineddata  /home/tulipan1637/Documents/Emiliano/OCR/OCRtraining/ocrd-train/usr/share/tessdata /foo.
Failed to read /home/tulipan1637/Documents/Emiliano/OCR/OCRtraining/ocrd-train/usr/share/tessdata
Makefile:97: recipe for target 'data/unicharset' failed
make: *** [data/unicharset] Error 1

I know it's a problem with my PATH but I don't really understand it. In that folder there are the .traineddata files. 

In the OCR group i got this reply:

```
_You have some problems with your path configuration, check the error message:

Failed to read /home/tulip/Documents/Em/OCR/OCRtraining/ocrd-train/usr/share/tessdata

the path does not make sense. And also the command line:

combine_tessdata -u /home/tulip/Documents/Em/OCR/OCRtraining/ocrd-train/usr/share/tessdata /foo.traineddata  /home/tulip/Documents/Em/OCR/OCRtraining/ocrd-train/usr/share/tessdata /foo.

you probably also have a "blank" after "/usr/share/tessdata".


Bye

Lorenzo_
```

But I still don't understand why this happens, what do I have to modify in the Makefile to make it work?

Thank you!

**Comment by kba** [comment]
It's a bug in the Makefile, there's a trailing space in the `TESSDATA` assignment. I'll fix it but I'm wondering why this hasn't happened to us. What platform are you on?
