### ISSUE TITLE
make: *** [data/unicharset] Error 

### ISSUE THREAD

**Issue by engahmed1190** [OCR-D/ocrd-train#20]
Hi @kba 

I have tried the code of tried 

```
combine_tessdata -u /mnt/e/projects/Training_Tesseract/ocrd-train/usr/share/tessdata/foo.traineddata  /mnt/e/projects/Training_Tesseract/ocrd-train/usr/share/tessdata/foo.
Failed to read /mnt/e/projects/Training_Tesseract/ocrd-train/usr/share/tessdata/foo.traineddata
Makefile:98: recipe for target 'data/unicharset' failed
```

I haven't seen any file called `foo.traineddata` in the `tessdata` directory. what do i need to do here 

when I change` foo.traineddata` with `eng.traineddata` . this command works fine which is expected as `combine_tessdata -u` extract exiting `traineddata` 
Thanks in advance

**Comment by Mayshinlyan** [comment]
Hi there,

I am also facing similar issues with Makefile:98. Can someone help please?

<img width="479" alt="capture" src="https://user-images.githubusercontent.com/25247629/43756016-8906d176-99c7-11e8-8391-db2a2e0a2590.PNG">

**Comment by kba** [comment]
Problem was that change introduced by #15 prevented creation of unicharset from scratch. For now, we do not set `CONTINUE_FROM` by default and create unicharset differently depending on whether `CONTINUE_FROM` is set.

@wrznr has some ideas how to improve that, hopefully we'll get around to implementing them soon.

**Comment by nebiyebln** [comment]
@kba hi please help me , I'm making a license plate recognition system. I will train tesseract to better read license plate characters. I created a data set for this. There are .tif and .txt files. but when I start the tutorial I get this error: unicharset_extractor: symbol lookup error: unicharset_extractor: undefined symbol: _ZN10UNICHARSET11null_scriptE
Makefile:103: recipe for target 'data/unicharset' failed
make: * [data/unicharset] Error 127

**Comment by wrznr** [comment]
@nebiyebln Pls. open an issue for your problem with a more detailed description of your problem, ideally in combination with a sample dataset which helps us to reproduce the problem.
