### ISSUE TITLE
Adding box file for whole page results a very high Error rate

### ISSUE THREAD

**Issue by engahmed1190** [OCR-D/ocrd-train#21]
Hello .

I am facing an issue related to the Error rate I have added box file contains many lines break them by `\t` but the Error rate is very high and the lstm model is not converging.

Here is a page sample example.

![image](https://user-images.githubusercontent.com/25582838/44519455-62bf2280-a6cd-11e8-81ac-5733a2253b52.png)

[train_sample.zip](https://github.com/OCR-D/ocrd-train/files/2313969/train_sample.zip)

**Comment by kba** [comment]
You need to train with line images. How did you generate the box file? See https://github.com/OCR-D/ocrd-train/issues/7 for some hints on how to segment lines with other tools for training with tesseract.

**Comment by engahmed1190** [comment]
@kba .
no way to train on full image .

**Comment by kba** [comment]
No, not at the moment, but we'll update #7 if/when we have any updates on this.
