### ISSUE TITLE
Generated .box files have identical coordinates for every character

### ISSUE THREAD

**Issue by jaddoughman** [OCR-D/ocrd-train#32]
### Environment:

tesseract 4.0.0
leptonica-1.76.0
 libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11
 Found AVX2
 Found AVX
 Found SSE

### Platfrom:
 Darwin Kernel Version 18.2.0 ; RELEASE_X86_64 x86_64

### Current Behavior:

Tesseract 4.0 using the best ara.traineddata file is recalling about 85% of the data, which is pretty good. I'm attempting to train Tesseract using Fine Tuning for impact. I used the GitHub project OCR-D Train to generate the .box and .lstmf files required for training, since my training data is composed of text line images. After generating the required .box and .lstmf files, I trained tesseract with a couple of lines to 400 iterations, but the the generated transcription with the fined tuned model looks a lot like 
"ل.َ1ح*جُ ح( .َو!ة.اع5 ّة'عآة'ا ن'جة.!ع. ”.َئءؤئجآ| ن!.5ل". I exhausted all the possibilities by training to max_iteration 0 and and a low target_error_rate, but the results were similar.

The transcription generated by the new model can be found below (Fine Tuned.txt):
[Fine Tuned.txt](https://github.com/tesseract-ocr/tesseract/files/2620169/Fine.Tuned.txt)

The transcription generated by the original Arabic model can be found below (Arabic Trained Model.txt): 
[Arabic Trained Model.txt](https://github.com/tesseract-ocr/tesseract/files/2620178/Arabic.Trained.Model.txt)

The fine tuned model can be found below (test1.traineddata):
[test1.traineddata.zip](https://github.com/tesseract-ocr/tesseract/files/2620182/test1.traineddata.zip)

I attempted to train from scratch using 4000 text line images, but they weren't enough to make a difference and didn't seem logical if your trained model is recalling more than 80% of my data. 

A sample of my training data which includes the .box and .lstmf is attached below: 
[training data.zip](https://github.com/tesseract-ocr/tesseract/files/2620231/training.data.zip)

**Comment by jaddoughman** [comment]
و 0 0 223 17 0
ن 0 0 223 17 0
ق 0 0 223 17 0
ل 0 0 223 17 0
ت 0 0 223 17 0
  0 0 223 17 0
ص 0 0 223 17 0
ح 0 0 223 17 0
ف 0 0 223 17 0
  0 0 223 17 0
ه 0 0 223 17 0
ن 0 0 223 17 0
د 0 0 223 17 0
ي 0 0 223 17 0
ة 0 0 223 17 0
  0 0 223 17 0
ا 0 0 223 17 0
م 0 0 223 17 0
س 0 0 223 17 0
  0 0 223 17 0

**Comment by amitdo** [comment]
>Generated .box files have identical coordinates for every character

It's Not a Bug, It's a Feature.

The LSTM engine needs only line boxes, If you'll give it char boxes, the first thing it will do is make line boxes from the char boxes info.

**Comment by jaddoughman** [comment]
But in my above given example of the .box file. It is generated as RTL not LTR. Will this create an issue wen finetuning ? If yes, will inverting the strings to LTR fix my issue ?

@amitdo

**Comment by amitdo** [comment]
About RTL the issue.

The ground truth text file needs to be converted from logical order to visual order.

https://www.unix.com/man-page/linux/1/fribidi

**Comment by jaddoughman** [comment]
I used fribidi to convert my ground truth in LTR order. The generated .box file is below. Is it normal that the coordinates come before the letter (not the case in English .box files) ?

LTR Ground Truth: ﻦﻴﺒﻧﺬﻤﻟﺍ ﺔﺒﻗﺎﻌﻣﻭ ﻝﺪﻌﻟﺍ ﻖﻴﻘﺤﺘﺑ" ﺪﻬﻌﺘﻳ ﻙﺭﺎﺒﻣ"
Generated .box File:
 ﻦ 0 0 894 67 0
ﻴ 0 0 894 67 0
ﺒ 0 0 894 67 0
ﻧ 0 0 894 67 0
ﺬ 0 0 894 67 0
ﻤ 0 0 894 67 0
ﻟ 0 0 894 67 0
ﺍ 0 0 894 67 0
  0 0 894 67 0
ﺔ 0 0 894 67 0
ﺒ 0 0 894 67 0
ﻗ 0 0 894 67 0
ﺎ 0 0 894 67 0
ﻌ 0 0 894 67 0
ﻣ 0 0 894 67 0
ﻭ 0 0 894 67 0
  0 0 894 67 0
ﻝ 0 0 894 67 0
ﺪ 0 0 894 67 0
ﻌ 0 0 894 67 0
ﻟ 0 0 894 67 0
ﺍ 0 0 894 67 0
  0 0 894 67 0
ﻖ 0 0 894 67 0
ﻴ 0 0 894 67 0
ﻘ 0 0 894 67 0
ﺤ 0 0 894 67 0
ﺘ 0 0 894 67 0
ﺑ 0 0 894 67 0
" 0 0 894 67 0
  0 0 894 67 0
ﺪ 0 0 894 67 0
ﻬ 0 0 894 67 0
ﻌ 0 0 894 67 0
ﺘ 0 0 894 67 0
ﻳ 0 0 894 67 0
  0 0 894 67 0
ﻙ 0 0 894 67 0
ﺭ 0 0 894 67 0
ﺎ 0 0 894 67 0
ﺒ 0 0 894 67 0
ﻣ 0 0 894 67 0
" 0 0 894 67 0
	 894 67 895 68 0

@amitdo

**Comment by jaddoughman** [comment]
After following your instructions and converting the .gt.txt file and generated .box file to LTR order. The training is looking a lot like this:

Iteration 459: ALIGNED TRUTH : 00000000 0000000 00000 000000" 00000 00000
Iteration 459: BEST OCR TEXT : 00000000 0000000 00000 000000" 00000 00000"
File data/train/line_1_5.lstmf page 0 (Perfect):
Mean rms=4.529%, delta=32.952%, train=72.624%(67.841%), skip ratio=0%
Iteration 460: ALIGNED TRUTH : 00000 0000 00 00000 0000
Iteration 460: BEST OCR TEXT : ل00000 0000 00 00000 0000
File data/train/line_1_7.lstmf page 0 :
Mean rms=4.522%, delta=32.882%, train=72.484%(67.737%), skip ratio=0%
Iteration 461: ALIGNED TRUTH : 000000000 0000000 00000 000000" 00000 00000
Iteration 461: BEST OCR TEXT : 00000000 0000000 00000 000000"  00000 0000
File data/train/line_1_5.lstmf page 0 (Perfect):
Mean rms=4.515%, delta=32.811%, train=72.342%(67.626%), skip ratio=0%
Iteration 462: ALIGNED TRUTH : 00000 0000 00 00000 0000
Iteration 462: BEST OCR TEXT : ل00000 0000 00 00000 0000

Can you explain the reason behind such an error. I will attach the txt and box files below.

[line_1_5.gt.txt](https://github.com/OCR-D/ocrd-train/files/2641246/line_1_5.gt.txt)

[line_1_7.gt.txt](https://github.com/OCR-D/ocrd-train/files/2641247/line_1_7.gt.txt)

[line_1_8.gt.txt](https://github.com/OCR-D/ocrd-train/files/2641248/line_1_8.gt.txt)

0 67 894 0 0 ﻦ
0 67 894 0 0 ﻴ
0 67 894 0 0 ﺒ
0 67 894 0 0 ﻧ
0 67 894 0 0 ﺬ
0 67 894 0 0 ﻤ
0 67 894 0 0 ﻟ
0 67 894 0 0 ﺍ
  0 0 894 67 0
0 67 894 0 0 ﺔ
0 67 894 0 0 ﺒ
0 67 894 0 0 ﻗ
0 67 894 0 0 ﺎ
0 67 894 0 0 ﻌ
0 67 894 0 0 ﻣ
0 67 894 0 0 ﻭ
  0 0 894 67 0
0 67 894 0 0 ﻝ
0 67 894 0 0 ﺪ
0 67 894 0 0 ﻌ
0 67 894 0 0 ﻟ
0 67 894 0 0 ﺍ
  0 0 894 67 0
0 67 894 0 0 ﻖ
0 67 894 0 0 ﻴ
0 67 894 0 0 ﻘ
0 67 894 0 0 ﺤ
0 67 894 0 0 ﺘ
0 67 894 0 0 ﺑ
" 0 0 894 67 0
  0 0 894 67 0
0 67 894 0 0 ﺪ
0 67 894 0 0 ﻬ
0 67 894 0 0 ﻌ
0 67 894 0 0 ﺘ
0 67 894 0 0 ﻳ
  0 0 894 67 0
0 67 894 0 0 ﻙ
0 67 894 0 0 ﺭ
0 67 894 0 0 ﺎ
0 67 894 0 0 ﺒ
0 67 894 0 0 ﻣ
" 0 0 894 67 0
	 894 67 895 68 0

**Comment by jaddoughman** [comment]
@wrznr 

I attached a small dataset of Arabic text lines and their ground truth below. They are in RTL direction. I need to fine tune the _best arabic trained data model. Any help in doing so would be extremely appreciated. 

[Dataset.zip](https://github.com/OCR-D/ocrd-train/files/2641441/Dataset.zip)

**Comment by jaddoughman** [comment]
@amitdo  

If i followed your instructions in changing the ground truth to LTR, wouldn't i have to invert the tiff images as well ? The text would be inverted when changed to LTR, wouldn't that be an issue when generating the .lstm files ?

**Comment by jaddoughman** [comment]
@amitdo @wrznr 

Should i convert only the .gt.txt to LTR or should i also convert the resultant .box files ? If so, what should be done for the images ? Shouldn't they match the inverted text files ?

**Comment by amitdo** [comment]
>Should i change the resultant box files 

The chars order in the box files should match the reversed ground truth text.  

("Hello everyone" in Hebrew):
`שלום לכולם`
=>
`םלוכל םולש`
=>
```
ם
ל
ו
כ
ל
 
ם
ו
ל
ש
```
>and/or the original (tif) files ?

No.

**Comment by jaddoughman** [comment]
@amitdo

Okay, the box files will automatically have the same order as the reversed txt file. But does it create an issue if in the box files, the coordiantes came before the letter. Even when changing the txt file to RTL, the resultant box files gave the format or ( 0 0 0 0 letter) not (letter 0 0 0 0). 0 being any coordiante.

**Comment by amitdo** [comment]
In which application do you watch the box file?

**Comment by jaddoughman** [comment]
@amitdo  

I open the box files using "ge dit" on Ubuntu 16.04

**Comment by amitdo** [comment]
Please provide an example (just one tif, text, reverse, box).

**Comment by jaddoughman** [comment]
The Sample folder contains the normal tif file with the reversed text file (as you recommended using fribidi) and the generated box files (automatically reversed when generated). 

[Sample.zip](https://github.com/OCR-D/ocrd-train/files/2643698/Sample.zip)

**Comment by wrznr** [comment]
Also many thanks from my side @amitdo for your support on that matter. I successfully "fine-tuned" tesseract's Fraktur model with the latest version of ocrd-train:
```shell
make -j4 training START_MODEL=Fraktur TESSDATA=/home/kmw/built/tessdata_best/script
```
Place your training images in `data/ground-truth`, choose the model you want to fine-tune as `START_MODEL`, the folder the model is located in as `TESSDATA` and you **should** be fine. Pls. note that I haven't had time to test the procedure with an RTL data set yet. Problems are likely to occur, especially since your gedit shows something else than @amitdo 's.

**Comment by amitdo** [comment]
>Problems are likely to occur, especially since your gedit shows something else than @amitdo 's.

I see it as he see it... but it still fine :-)

**Comment by amitdo** [comment]
@wrznr, FYI,  Tesseract official lstm data was trained with **degraded** synthetic images.
https://github.com/tesseract-ocr/tesseract/issues/1052

**Comment by jaddoughman** [comment]
@amitdo @wrznr 
I used the dataset that @amitdo approved off and attempted to fine tune the arabic _best model...

Iteration 700: ALIGNED TRUTH : عامتجا ماتخ يف رداقلا دبع اعدو
Iteration 700: BEST OCR TEXT :  َجع 
File data/train/line_1_34.lstmf page 0 :
Mean rms=5.762%, delta=74.89%, train=184.604%(99.745%), skip ratio=0%
Iteration 701: ALIGNED TRUTH : عامتجلا 0ا للا 0خ "هنأ ًاحضوم تاعاس
Iteration 701: BEST OCR TEXT :  َو  
File data/train/line_1_30.lstmf page 0 :
Mean rms=5.76%, delta=74.83%, train=184.479%(99.745%), skip ratio=0%
Iteration 702: ALIGNED TRUTH : عباتي كرابم نا ادكؤم ،هددصلا
Iteration 702: BEST OCR TEXT : ْاةع

What is the issue ? I have been attempting to fine tune for more than 2 weeks, the results are very disappointing. Any help would be really appreciated.

**Comment by wrznr** [comment]
Really hard to tell from distance. Three things I have noticed: 1. Do not expect any good results before the let's say 2000th iteration. 2. The TIFs in `Dataset.zip` are rather small in terms of file size (mostly about 3k while our sample line images are about 14k). 3. I could not open them with Ubuntu's standard image viewer: 
![image](https://user-images.githubusercontent.com/26707219/49458915-20d66a00-f7ee-11e8-8e8c-fe3286488994.png)

And, as I mentioned above, there is the issue of different gedit behaviors.This is what it looks like in may gedit: 
![image](https://user-images.githubusercontent.com/26707219/49459103-8cb8d280-f7ee-11e8-9884-5fc58c3c6863.png)

Correct or not?

**Comment by jaddoughman** [comment]
@wrznr  

1) You can open the tif images using the Shotwell viewer (pre-installed with Ubuntu).
2) Concerning the size, i can generate more than 3k text lines easily, but for fine tuning i don't think that a large dataset is needed. Your Makefile is used for Training From Scratch i believe.
3) The dataset.zip file contains the txt files in RTL order, this was before i used fribidi to convert them to LTR. Do not attempt to train with them. 

Can you elaborate on the functionality of your Makefile, are you fine tuning or training from scratch ?

**Comment by jaddoughman** [comment]
@wrznr  

Also, concerning the bidirectional support, I can gladly edit your python script to enable its support of bidirectional text lines. This would be a major upgrade since training for Bidirectional languages is extremely useful.

**Comment by wrznr** [comment]
Your support is very welcome. If you file a pull request for bidi language support, we will gladly merge it. The makefile is supposed to support both, training from scratch as well as starting with a previously built model. With 3k, I reffered to individual file size rather than training set size.

**Comment by wrznr** [comment]
@jaddoughman I do not have much experience with training productive models myself. Sorry. When we set up this repository, our hope was that we could get some of the necessary insights from users like you... But my guess would be that 3k text lines are enough to fine tune an existing model.

> With 3k, I referred to individual file size rather than training set size.

**File** size not image size (a line in our example data set has typically about 13kb while your's have only 3kb). It might well be that the resolution of the images is to small. It should be at least 300dpi. But again, my experience is rather limited.
