### ISSUE TITLE
TESSDATA_REPO needs to be tessdata_best

### ISSUE THREAD

**Issue by Shreeshrii** [OCR-D/ocrd-train#55]
# Tesseract model repo to use. Default: $(TESSDATA_REPO)
TESSDATA_REPO = _fast

_fast models are integer models and can NOT be used as base for finetuning. Only models from tessdata_best can be used for this.

**Comment by ameera3** [comment]
This is really important.  In the Makefile, you must change

# Tesseract model repo to use. Default: $(TESSDATA_REPO)
TESSDATA_REPO = _fast

to

# Tesseract model repo to use. Default: $(TESSDATA_REPO)
TESSDATA_REPO = tessdata_best

Otherwise, your training error will be very high.

**Comment by ameera3** [comment]
One more thing.  In the Makefile, the URL for english tessdata best is 

https://github.com/tesseract-ocr/tessdata$(TESSDATA_REPO)/raw/master/$(notdir $@)

But it should be

https://github.com/tesseract-ocr/$(TESSDATA_REPO)/raw/master/$(notdir $@)

See [https://github.com/tesseract-ocr/tessdata_best](url)
