### ISSUE TITLE
make training errors with sample ground truth 

### ISSUE THREAD

**Issue by ameera3** [OCR-D/ocrd-train#57]
I have extracted ocrd-testset.zip to ./data/ground-truth.

I type the commands:
root@CUDA1:/home/ocrd-train# export PYTHONIOENCODING=utf8
root@CUDA1:/home/ocrd-train# make training

Output:
tesseract data/ground-truth/alexis_ruhe01_1852_0018_022.tif data/ground-truth/alexis_ruhe01_1852_0018_022 --psm 6 lstm.train
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Page 1
Warning. Invalid resolution 0 dpi. Using 70 instead.
Failed to read boxes from data/ground-truth/alexis_ruhe01_1852_0018_022.tif
.
.
.
tesseract data/ground-truth/wienbarg_feldzuege_1834_0318_006.tif data/ground-truth/wienbarg_feldzuege_1834_0318_006 --psm 6 lstm.train
Tesseract Open Source OCR Engine v4.0.0-beta.1 with Leptonica
Page 1
Warning. Invalid resolution 0 dpi. Using 70 instead.
Failed to read boxes from data/ground-truth/wienbarg_feldzuege_1834_0318_006.tif
find data/ground-truth -name '*.lstmf' -exec echo {} \; | sort -R -o "data/all-lstmf"
total=`cat data/all-lstmf | wc -l` \
   no=`echo "$total * 0.90 / 1" | bc`; \
   head -n "$no" data/all-lstmf > "data/list.train"
/bin/bash: bc: command not found
head: invalid number of lines: ''
Makefile:84: recipe for target 'data/list.train' failed
make: *** [data/list.train] Error 1

The list.train file is empty.  Does anyone know how to fix this?

**Comment by ameera3** [comment]
[https://groups.google.com/forum/#!searchin/tesseract-ocr/OCR-D%7Csort:date/tesseract-ocr/-F8KpHLSHRk/X4TXfXWUHgAJ](url)

**Comment by cooleel** [comment]
Hi @ameera3 , I met the similar problem, the link you posted above is invalid now, could you please share your solution? Thanks.

**Comment by ameera3** [comment]
Instead of clicking on the link, copy and paste it into your browser.  You need to install the bc package and whatever other packages are missing.  Hope that helps!
