### ISSUE TITLE
`make training` gave me this error

### ISSUE THREAD

**Issue by akilesh96** [OCR-D/ocrd-train#59]
tesseract data/ground-truth/alexis_ruhe01_1852_0087_027.tif data/ground-truth/alexis_ruhe01_1852_0087_027 --psm 6 lstm.train
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Tesseract Open Source OCR Engine v4.0.0-beta.3 with Leptonica
Error in findTiffCompression: function not present
Error in pixReadFromMultipageTiff: function not present

**Comment by akilesh96** [comment]
/home/name/Desktop/ocrd-train-master/usr/bin/tesseract --version
tesseract 4.0.0-beta.3
 leptonica-1.75.3
  libpng 1.6.34 : zlib 1.2.11

 Found AVX
 Found SSE

**Comment by akilesh96** [comment]
/home/name/Desktop/ocrd-train-master/usr/bin/tesseract --version
tesseract 4.0.0-beta.3
 leptonica-1.75.3
  libpng 1.6.34 : zlib 1.2.11

 Found AVX
 Found SSE

libtiff is missing...

**Comment by wrznr** [comment]
Yes! As you say: `libtiff` is missing. Please install it and rebuild/reinstall tesseract. This is not an `ocrd-train` issue.
