### ISSUE TITLE
Warning: LSTMTrainer deserialized an LSTMRecognizer!

### ISSUE THREAD

**Issue by jayawantkarale** [OCR-D/ocrd-train#60]
### I am training marathi language but i am getting following warning which resulting in training error rate around 100%

Log generated during training

Warning: LSTMTrainer deserialized an LSTMRecognizer!
Loaded 1/1 pages (1-1) of document data/ground-truth/bori-g0351-14-026.exp0.lstmf
At iteration 1189/1200/1200, Mean rms=6.836%, delta=55.863%, char train=111.93%, word train=99.35%, skip ratio=0%,  New worst char error = 111.93 wrote checkpoint.

Loaded 1/1 pages (1-1) of document data/ground-truth/bori-g0351-14-014.exp0.lstmf
Warning: LSTMTrainer deserialized an LSTMRecognizer!
At iteration 1289/1300/1300, Mean rms=6.812%, delta=55.992%, char train=111.945%, word train=98.95%, skip ratio=0%,  New worst char error = 111.945At iteration 1090, stage 0, Eval Char error rate=100, Word error rate=100 wrote checkpoint.

Warning: LSTMTrainer deserialized an LSTMRecognizer!
At iteration 1389/1400/1400, Mean rms=6.806%, delta=56.201%, char train=114.316%, word train=98.65%, skip ratio=0%,  New worst char error = 114.316At iteration 1189, stage 0, Eval Char error rate=100, Word error rate=100 wrote checkpoint.
.
.
.
.
.
.

Finished! Error rate = 87.055
debug_interval -1
/bin/bash: debug_interval: command not found
make: [Makefile:148: data/checkpoints/mar10_checkpoint] Error 127 (ignored)

**Comment by wrznr** [comment]
There may be something wrong with your setup. From the information provided above, it is not possible to judge.

**Comment by cuonghust** [comment]
> There may be something wrong with your setup. From the information provided above, it is not possible to judge.

I have same this behavior. And Error rate is 92% :(
From me: I training handwriting text of Vietnamese language, volume of data is 1800 images. My data too small ? or any things need to more config with Vietnamese language when training ?

Thank you !

**Comment by wrznr** [comment]
@cuonghust Sorry, but I do not have any experience with handwriting recognition and Tesseract. I am not sure whether Tesseract is good choice for this task. And again:

> There may be something wrong with your setup. From the information provided above, it is not possible to judge.

**Comment by wrznr** [comment]
Btw.: The warning `Warning: LSTMTrainer deserialized an LSTMRecognizer!` is expected and no reason to worry.

**Comment by wrznr** [comment]
Pls. reopen if the problem persists and you can offer more detailed information.

**Comment by mark-galvin** [comment]
This is an old post however  I just ran into this and I think I have the answer.   

This warning (not really a warning) occurs only on the first training attempt because there were no previous iteration to deserialize
Line:  438
[lstmtrainer.cpp](https://tesseract-ocr.github.io/tessapi/5.x/a01325_source.html)


```
 // Reads from the given file. Returns false in case of error.
 // NOTE: It is assumed that the trainer is never read cross-endian.
 bool LSTMTrainer::DeSerialize(const TessdataManager* mgr, TFile* fp) {
   if (!LSTMRecognizer::DeSerialize(mgr, fp)) return false;
   if (!fp->DeSerialize(&learning_iteration_)) {
     // Special case. If we successfully decoded the recognizer, but fail here
     // then it means we were just given a recognizer, so issue a warning and
     // allow it.
     tprintf("Warning: LSTMTrainer deserialized an LSTMRecognizer!\n");
     learning_iteration_ = 0;
     network_->SetEnableTraining(TS_ENABLED);
     return true;
   }
```
