### ISSUE TITLE
make training fails on load script for unicharset

### ISSUE THREAD

**Issue by torhhu** [OCR-D/ocrd-train#61]
I get an error when running `make training`. It seems to insert an extra "/" in the reference to the data directory in one of the steps. Running on Ubuntu 18.04 in a Docker container.

Loaded unicharset of size 79 from file data/unicharset
Setting unichar properties
Other case I of i is not in unicharset
Other case Ä of ä is not in unicharset
Other case Ö of ö is not in unicharset
Other case Uͤ of uͤ is not in unicharset
Other case Aͤ of aͤ is not in unicharset
Other case Oͤ of oͤ is not in unicharset
Other case Y of y is not in unicharset
Setting script properties
Failed to load script unicharset from:**data//Latin.unicharset**

**Comment by wrznr** [comment]
Please provide more information. I am not able reproduce this one.

**Comment by torhhu** [comment]
I deleted everything from the data directory except for the GT folder (but including the .box files in that folder) and rerunning now. It seems to work as expected now. So this issue can be closed and/or deleted

**Comment by wrznr** [comment]
Thanks.
