### ISSUE TITLE
the libtiff 5 is upto date what do i do

### ISSUE THREAD

**Issue by shreenidhimc** [OCR-D/ocrd-train#67]
tesseract data/ground-truth/001.tif data/ground-truth/001 --psm 6 lstm.train
Error in pixReadMemTiff: function not present
Error in pixReadMem: tiff: no pix returned
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
Tesseract Open Source OCR Engine v4.0.0-beta.3 with Leptonica
Error in pixReadStreamJpeg: function not present
Error in pixReadStream: jpeg: no pix returned
Error in pixRead: pix not read
Error during processing.
Makefile:117: recipe for target 'data/ground-truth/001.lstmf' failed
make: *** [data/ground-truth/001.lstmf] Error 1

**Comment by 20Aditya** [comment]
> tesseract data/ground-truth/001.tif data/ground-truth/001 --psm 6 lstm.train
> Error in pixReadMemTiff: function not present
> Error in pixReadMem: tiff: no pix returned
> Error in pixaGenerateFontFromString: pix not made
> Error in bmfCreate: font pixa not made
> Tesseract Open Source OCR Engine v4.0.0-beta.3 with Leptonica
> Error in pixReadStreamJpeg: function not present
> Error in pixReadStream: jpeg: no pix returned
> Error in pixRead: pix not read
> Error during processing.
> Makefile:117: recipe for target 'data/ground-truth/001.lstmf' failed
> make: *** [data/ground-truth/001.lstmf] Error 1

Hi, Have you found a solution to this problem???

**Comment by wrznr** [comment]
I think this could be an issue with your tesseract/leptonica build. `libtiff` has to be present at build time. I cannot reproduce this behavior at my machine.
